### ISSUE TITLE
Please use DateTimeInterface instead of DateTime

### ISSUE THREAD

**Issue by georgehrke** [punic/punic#109] opened 2017-11-02 13:10 UTC
When I hand over a [DateTimeImmutable](http://php.net/manual/en/class.datetimeimmutable.php) object to Punic, it throws an exception.

Please use the [DateTimeInterface](http://php.net/manual/en/class.datetimeinterface.php) when checking the type instead of DateTime.

**Comment by mlocati** [comment] 2017-11-02 14:46
...the minimum PHP version supported by Punic is 5.3, where `DateTimeImmutable` doesn't exist...

**Comment by georgehrke** [comment] 2017-11-02 15:02
PHP 5.3 is EOL for years now: http://php.net/supported-versions.php
Maybe you should reconsider the minimum PHP version

**Comment by mlocati** [comment] 2017-11-02 15:26
I may do that, but this library has a very wide usage: I can't assume that every user can/want to upgrade their PHP.

**Comment by georgehrke** [comment] 2017-11-02 15:32
I see your point, but you could just release 3.0 which increases the minimum version to PHP 5.5, but keep support for the 2.x branch at the same time.

**Comment by mlocati** [comment] 2017-11-02 16:10
I could do that. The problem is that I have very little spare time. I hardly find time to maintain one release: maintaining two series is impossible at the moment. But keep this issue open, so that when (if?) I'll have time I'll do that

**Comment by mlocati** [comment] 2018-01-22 13:25
Fixed in #115 (real author is @c960657)

**Closed by mlocati** 2018-01-22 13:25 UTC
